Add skip button in wizard
Codeinwp/wp-maintenance-mode pull request #351
Opened 2022-12-13 22:12 UTC by arinaturcu

## Summary
- Adds a skip button in the wizard to let the user skip importing a template and installing Otter
- Adds a notice in the wizard and in the design tab to announce that, by importing a template, Otter will be installed and activated.
- The text in the skip button changes depending on the selected template type (maintenance / coming soon / landing page)

## Screenshots
<img width="600" alt="Screenshot 2022-12-14 at 00 11 03" src="https://user-images.githubusercontent.com/39873395/207454950-acad08e3-c107-4dd3-8899-9abf1e9c6f46.png">
<img width="600" alt="Screenshot 2022-12-14 at 00 12 01" src="https://user-images.githubusercontent.com/39873395/207455147-4ba0b4c8-6844-4638-95f8-9b3f8c795d20.png">

## Test instructions
- By clicking the `I don’t want to use a template` button from the wizard, the user is taken to the next step, which is the Subscribe step, and then directly to the settings page (skipping the last usual step)
- After this, Otter should not be added to the plugins list

Closes #345.

2022-12-14 10:38 UTC, HardeepAsrani requested changes
I see the Otter message appears even if Otter is already active. We don't need to show it if Otter already exists.

2022-12-14 15:39 UTC, arinaturcu commented
Thanks @HardeepAsrani! I've changed it now it only shows if Otter is not active.

2022-12-14 18:48 UTC, HardeepAsrani commented on views/settings.php
> +							if ( ! is_plugin_active( 'otter-blocks/otter-blocks.php' ) ) {
It's not the best way to detect as someone might have Otter with a different folder name, you can also maybe check this *OR* `OTTER_BLOCKS_VERSION` constant.

2022-12-14 18:48 UTC, HardeepAsrani commented on views/settings.php
> +							if ( ! is_plugin_active( 'otter-blocks/otter-blocks.php' ) ) {
After that you can put it for QA.

2022-12-15 09:26 UTC, irinelenache commented
@arinaturcu Tested the enhancement and here is what i found:

- [ ] If Otter is not installed, the buttons will be at the [bottom of the screen](https://vertis.d.pr/i/mLCm5t), maybe we can add some bottom margin there

2022-12-15 20:17 UTC, arinaturcu commented
Thank you @irinelenache!
It's fixed now, let me now if there is anything else.

2022-12-16 07:44 UTC, irinelenache commented
@arinaturcu Everything's fine now, thank you 🚀

2022-12-16 17:02 UTC, merged